var express = require('express');
var router = express.Router();
var UserLevel = require('../models/UserLevel');

router.get('/:id?',function(req,res,next){
	if(req.params.id){
		UserLevel.getLevelByNo(req.params.id,function(err,rows){
			if(err){
				res.json(err);
			}
			else{
				res.json(rows);
			}
		});
	}
	else{
		UserLevel.getAllLevels(function(err,rows){
			if(err){
				res.json(err);
			}
			else{
				res.json(rows);
			}
		});
	}
});
router.post('/',function(req,res,next){
	UserLevel.addLevel(req.body,function(err,count){
		if(err){
			res.json(err);
		}
		else{
			res.json(req.body);
		}
	});
});
router.delete('/:id',function(req,res,next){
	UserLevel.removeLevel(req.params.id,function(err,count){
		if(err){
			res.json(err);
		}
		else{
			res.json(count);
		}
	});
});
/*router.put('/:id',function(req,res,next){
	UserTemp.updateStaff(req.params.id,req.body,function(err,rows){
		if(err){
			res.json(err);
		}
		else{
			res.json(rows);
		}
	});
});*/
module.exports=router;